export const getTeamName = (teamAbbrev: string) => teamsAbbr[teamAbbrev]

const teamsAbbr: { [key: string]: string } = {
	ANA: 'Ducks',
	ARI: 'Coyotes',
	BOS: 'Bruins',
	BUF: 'Sabres',
	CGY: 'Flames',
	CAR: 'Hurricanes',
	CHI: 'Blackhawks',
	COL: 'Avalanche',
	CBJ: 'Blue Jackets',
	DAL: 'Stars',
	DET: 'Red Wings',
	EDM: 'Oilers',
	FLA: 'Panthers',
	LAK: 'Kings',
	MIN: 'Wild',
	MTL: 'Canadiens',
	NJD: 'Devils',
	NYI: 'Islanders',
	NYR: 'Rangers',
	NSH: 'Predators',
	OTT: 'Senators',
	PHI: 'Flyers',
	PIT: 'Penguins',
	SEA: 'Kraken',
	SJS: 'Sharks',
	STL: 'Blues',
	TBL: 'Lightning',
	TOR: 'Maple Leafs',
	VAN: 'Canucks',
	VGK: 'Golden Knights',
	WSH: 'Capitals',
	WPG: 'Jets',
}
